# Generated by Django 5.1.3 on 2024-12-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_programmer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1)),
                ('N_ficha', models.IntegerField(max_length=7)),
                ('formacion', models.BooleanField(default=True)),
                ('f_ingreso', models.DateField(default=None)),
            ],
        ),
    ]
